### ISSUE TITLE
Network discovery errors on iOS16

### ISSUE THREAD

**Issue by mrphilipandrews** [Zebra/LinkOS-iOS-Samples#8]
getting an error from ```[NetworkDiscoverer localBroadcast:&error]```on ios16 devices. works on ios15 and ios16 simulator

![IMG_EB51BE89C63C-1](https://user-images.githubusercontent.com/505776/197082933-f9d4ba0c-d17b-4d2c-85d4-35283c79df99.jpeg)
![Screen Shot 2022-10-20 at 1 36 02 pm](https://user-images.githubusercontent.com/505776/197082950-58017a96-8ab5-47d5-af04-7c0790d27104.png)

**Comment by ssizebra** [comment]
The local network privacy has been enforced on iOS 16. The network discover uses the UDP multicast, which is blocked on iOS16 by default unless the app has the network multicast entitlement. See this article for details: [Link-OS SDK for iOS – Printer Network Discovery API impacted by iOS 14.5 and higher](https://developer.zebra.com/blog/link-os-sdk-ios-printer-network-discovery-api-impacted-ios-145-and-higher). Please follow up with Apple for the network entitlement for your app.

**Comment by mrphilipandrews** [comment]
hi, thanks the response @ssizebra 

to clarify we are not using `NetworkDiscoverer multicastWithHops` we are seeing the error in `NetworkDiscoverer localBroadcast` . Do we need the Multicast Network Entitlement request for this too? It works fine for us in ios15, its only failing on ios16 physical device.

if you add the error option to the demo app, you can see the failure

https://github.com/ZebraDevs/LinkOS-iOS-Samples/blob/ZSDK_DevDemos/ZSDK_DevDemos/Classes/DiscoveryViewController.m#L97

```
- (void)doLocalBroadcast {
	NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
	[self performSelectorOnMainThread:@selector(startSpinner) withObject:nil waitUntilDone:YES];
        NSError *error = nil;
	self.printers = [NetworkDiscoverer localBroadcast:&error];
```



![Screen Shot 2022-10-21 at 2 55 46 pm](https://user-images.githubusercontent.com/505776/197108194-afba239e-30a8-4580-8863-56fbc8520bb3.png)

**Comment by ssizebra** [comment]
@fatlinesofcode, The underneath implementation of the network discovery utilizes the UDP socket to broadcast the discovery request on the network. If the IP address the discovery request is sent on is the multicast IP address, the discovery becomes the multicast discovery. If the IP address is the local broadcast IP address, it becomes a local broadcast discovery. The network entitlement is request for any UDP broadcast. See this FAQ by Apple: https://developer.apple.com/forums/thread/663875

**Comment by mrphilipandrews** [comment]
thanks, i see the faq has this which explained why it wasnt effected on ios15

_IMPORTANT Due to a combination of implementation limitations and bugs, not all of the these restrictions are enforced on iOS 14 and 15. They should be correctly enforced by iOS 16 and later. Please [let us know](https://developer.apple.com/forums/thread/712889) if you find evidence to the contrary._
